name: Profile Image Replacer
on:
  schedule:
    # NOTE: Until GH Actions supports timezone lets do a conversion for now
    - cron: '0 21 * * *' # 9PM UTC = 5AM PH
    - cron: '0 4 * * *' # 4AM UTC  = 12PM PH
    - cron: '0 15 * * *' # 3PM UTC = 11PM PH
  workflow_dispatch:
    


jobs:
  image-replacer:
    runs-on: ubuntu-latest
    steps:
      - env:
          SCHEDULE : ${{ github.event.schedule }}
        run: |
          echo $SCHEDULE

      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz

      - name: Run Image Replacer Script
        run: |
          cd ./scripts
          python image-replacer.py 
      
      - name: Commit Message
        id: commit-message
        run: |
          cd ./scripts
          sudo ./commit-message.sh $SCHEDULE

      - name: Commit Changes
        run: |
          git config --global user.email 'jec.castanos@gmail.com'
          git config --global user.name 'jscastanos'
          git add .
          git commit -m "chore[BOT]: ${{ steps.commit-message.outputs.COMMIT_MESSAGE }}"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true 