name: "Label"
on:
  pull_request:
    types: [synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: label
        run: |
          echo "${{ toJson(github.event.pull_request.labels.*.name) }}"
          echo ${{ contains(toJson(github.event.pull_request.labels.*.name), 'for review') }}



    