name: "PR Comment"
on:
  pull_request_review_comment:
    types:
      - "created"
  pull_request_review:
    types:
      - "submitted"

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: comment
        run: echo "comment"

    