name: "Test"
on:
  pull_request:
    types: [synchronize]

jobs:
  test:
    if: contains(toJson(github.event.pull_request.labels.*.name), 'for review')
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test"



    